---
name: pr pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: 🛠️ Test Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: codebeltnet/dotnet-restore@v2

      - name: Build for Preview
        uses: codebeltnet/dotnet-build@v2
        with:
          configuration: Debug

